# Generated by Django 5.2.1 on 2025-08-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_capo_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorddiagram',
            name='capo_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
