# Generated by Django 5.2.1 on 2025-08-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chorddiagram_capo_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='roman_numeral',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
