# Generated by Django 5.2.1 on 2025-09-15 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chord_roman_numeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('finger', models.IntegerField(choices=[(0, 'Open/Muted'), (1, 'Index'), (2, 'Middle'), (3, 'Ring'), (4, 'Pinky'), (5, 'Thumb')], default=0)),
            ],
            options={
                'ordering': ['string_number'],
            },
        ),
        migrations.CreateModel(
            name='FretPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('fret_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
            ],
            options={
                'ordering': ['string_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.BigIntegerField(default=0)),
                ('daily_plays', models.IntegerField(default=0)),
                ('weekly_plays', models.IntegerField(default=0)),
                ('monthly_plays', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('last_daily_reset', models.DateField(auto_now_add=True)),
                ('last_weekly_reset', models.DateField(auto_now_add=True)),
                ('last_monthly_reset', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chord',
            options={'ordering': ['measure', 'beat', 'sub_beat']},
        ),
        migrations.AlterModelOptions(
            name='songrequest',
            options={'ordering': ['-priority', '-requested_at']},
        ),
        migrations.AlterUniqueTogether(
            name='chord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chorddiagram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chord',
            name='duration_in_beats',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='chord',
            name='inversion',
            field=models.CharField(choices=[('root', 'Root Position'), ('first', 'First Inversion'), ('second', 'Second Inversion'), ('third', 'Third Inversion')], default='root', max_length=10),
        ),
        migrations.AddField(
            model_name='chord',
            name='key_context',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chord',
            name='measure',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='chord',
            name='quality',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('diminished', 'Diminished'), ('augmented', 'Augmented'), ('dominant7', 'Dominant 7th'), ('major7', 'Major 7th'), ('minor7', 'Minor 7th'), ('minor7b5', 'Minor 7th ♭5'), ('diminished7', 'Diminished 7th'), ('sus2', 'Suspended 2nd'), ('sus4', 'Suspended 4th'), ('add9', 'Add 9th'), ('6', '6th'), ('minor6', 'Minor 6th')], default='major', max_length=20),
        ),
        migrations.AddField(
            model_name='chord',
            name='root',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C#/D♭'), ('D', 'D'), ('D#', 'D#/E♭'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/G♭'), ('G', 'G'), ('G#', 'G#/A♭'), ('A', 'A'), ('A#', 'A#/B♭'), ('B', 'B')], default='C', max_length=3),
        ),
        migrations.AddField(
            model_name='chord',
            name='sub_beat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='chorddiagram',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chorddiagram',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele'), ('bass', 'Bass'), ('mandolin', 'Mandolin')], default='guitar', max_length=20),
        ),
        migrations.AddField(
            model_name='chorddiagram',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this chord shape'),
        ),
        migrations.AddField(
            model_name='song',
            name='time_signature',
            field=models.CharField(choices=[('4/4', '4/4'), ('3/4', '3/4'), ('2/4', '2/4'), ('6/8', '6/8'), ('12/8', '12/8'), ('5/4', '5/4'), ('7/8', '7/8')], default='4/4', max_length=10),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='Link to existing artist if found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.artist'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Link to existing genre if found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genre'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='priority',
            field=models.IntegerField(default=5, help_text='Priority level 1-10 (10 = highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='chord',
            name='beat',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='chord',
            name='chord_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chorddiagram',
            name='fingers',
            field=models.JSONField(help_text='Finger positions for each string'),
        ),
        migrations.AlterField(
            model_name='chorddiagram',
            name='frets',
            field=models.JSONField(help_text='Fret positions for each string'),
        ),
        migrations.AlterUniqueTogether(
            name='chorddiagram',
            unique_together={('chord_name', 'tuning', 'instrument')},
        ),
        migrations.AddIndex(
            model_name='chorddiagram',
            index=models.Index(fields=['chord_name', 'instrument'], name='api_chorddi_chord_n_aa8b16_idx'),
        ),
        migrations.AddIndex(
            model_name='chorddiagram',
            index=models.Index(fields=['difficulty'], name='api_chorddi_difficu_9c3096_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['status', 'priority'], name='api_songreq_status_0c26e1_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['requested_at'], name='api_songreq_request_7a7c28_idx'),
        ),
        migrations.AddField(
            model_name='fingerposition',
            name='chord_diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_positions', to='api.chorddiagram'),
        ),
        migrations.AddField(
            model_name='fretposition',
            name='chord_diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fret_positions', to='api.chorddiagram'),
        ),
        migrations.AddField(
            model_name='playcount',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_stats', to='api.song'),
        ),
        migrations.RemoveField(
            model_name='chord',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='fingerposition',
            unique_together={('chord_diagram', 'string_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fretposition',
            unique_together={('chord_diagram', 'string_number')},
        ),
    ]
