# Generated by Django 5.2.1 on 2025-09-16 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_inconsistent_chord_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fingerposition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fingerposition',
            name='chord_diagram',
        ),
        migrations.AlterUniqueTogether(
            name='fretposition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fretposition',
            name='chord_diagram',
        ),
        migrations.RemoveField(
            model_name='playcount',
            name='song',
        ),
        migrations.AlterModelOptions(
            name='chord',
            options={'ordering': ['measure', 'beat', 'sub_beat'], 'verbose_name': 'Chord', 'verbose_name_plural': 'Chords'},
        ),
        migrations.AlterModelOptions(
            name='songrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveIndex(
            model_name='chorddiagram',
            name='api_chorddi_chord_n_aa8b16_idx',
        ),
        migrations.RemoveIndex(
            model_name='chorddiagram',
            name='api_chorddi_difficu_9c3096_idx',
        ),
        migrations.RemoveIndex(
            model_name='songrequest',
            name='api_songreq_status_0c26e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='songrequest',
            name='api_songreq_request_7a7c28_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chorddiagram',
            unique_together={('chord_name', 'tuning')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='time_signature',
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='priority',
        ),
        migrations.AddField(
            model_name='chord',
            name='extensions',
            field=models.CharField(blank=True, help_text="Additional chord modifiers (e.g., '7', 'sus4', 'add9')", max_length=50),
        ),
        migrations.AlterField(
            model_name='chord',
            name='beat',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Beat within measure', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='chord',
            name='chord_name',
            field=models.CharField(blank=True, help_text='Auto-generated chord name', max_length=50),
        ),
        migrations.AlterField(
            model_name='chord',
            name='duration_in_beats',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Duration in beats', max_digits=4),
        ),
        migrations.AlterField(
            model_name='chord',
            name='inversion',
            field=models.CharField(choices=[('root', 'Root Position'), ('first', 'First Inversion'), ('second', 'Second Inversion'), ('third', 'Third Inversion')], default='root', help_text='Chord inversion', max_length=10),
        ),
        migrations.AlterField(
            model_name='chord',
            name='key_context',
            field=models.CharField(blank=True, help_text='Key signature for roman numeral context', max_length=20),
        ),
        migrations.AlterField(
            model_name='chord',
            name='measure',
            field=models.IntegerField(default=1, help_text='Measure number (1-based)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chord',
            name='quality',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('diminished', 'Diminished'), ('augmented', 'Augmented'), ('dominant7', 'Dominant 7th'), ('major7', 'Major 7th'), ('minor7', 'Minor 7th'), ('minor7b5', 'Minor 7th ♭5'), ('diminished7', 'Diminished 7th'), ('sus2', 'Suspended 2nd'), ('sus4', 'Suspended 4th'), ('add9', 'Add 9th'), ('6', '6th'), ('minor6', 'Minor 6th')], help_text="Chord type (e.g., 'major', 'minor', 'diminished')", max_length=20),
        ),
        migrations.AlterField(
            model_name='chord',
            name='roman_numeral',
            field=models.CharField(blank=True, help_text='Roman numeral (I, ii, V, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='chord',
            name='root',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C#/D♭'), ('Db', 'D♭/C#'), ('D', 'D'), ('D#', 'D#/E♭'), ('Eb', 'E♭/D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#/G♭'), ('Gb', 'G♭/F#'), ('G', 'G'), ('G#', 'G#/A♭'), ('Ab', 'A♭/G#'), ('A', 'A'), ('A#', 'A#/B♭'), ('Bb', 'B♭/A#'), ('B', 'B')], help_text="Base note of the chord (e.g., 'C', 'A')", max_length=3),
        ),
        migrations.AlterField(
            model_name='chord',
            name='sub_beat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Subdivision of beat', max_digits=4),
        ),
        migrations.AlterField(
            model_name='chorddiagram',
            name='fingers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='chorddiagram',
            name='frets',
            field=models.JSONField(),
        ),
        migrations.AlterUniqueTogether(
            name='chord',
            unique_together={('song', 'measure', 'beat', 'sub_beat')},
        ),
        migrations.DeleteModel(
            name='FingerPosition',
        ),
        migrations.DeleteModel(
            name='FretPosition',
        ),
        migrations.DeleteModel(
            name='PlayCount',
        ),
        migrations.RemoveField(
            model_name='chorddiagram',
            name='alternative_name',
        ),
        migrations.RemoveField(
            model_name='chorddiagram',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='chorddiagram',
            name='notes',
        ),
    ]
