# Generated by Django 5.2.1 on 2025-09-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_extensions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='quality',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('diminished', 'Diminished'), ('augmented', 'Augmented'), ('dominant7', 'Dominant 7th'), ('major7', 'Major 7th'), ('minor7', 'Minor 7th'), ('minor7b5', 'Minor 7th ♭5'), ('diminished7', 'Diminished 7th'), ('augmented7', 'Augmented 7th'), ('major7#5', 'Major 7th ♯5'), ('sus2', 'Suspended 2nd'), ('sus4', 'Suspended 4th'), ('sus2sus4', 'Suspended 2nd & 4th'), ('add9', 'Add 9th'), ('add11', 'Add 11th'), ('add13', 'Add 13th'), ('6', '6th'), ('minor6', 'Minor 6th'), ('major6', 'Major 6th'), ('9', '9th'), ('major9', 'Major 9th'), ('minor9', 'Minor 9th'), ('dominant9', 'Dominant 9th'), ('11', '11th'), ('major11', 'Major 11th'), ('minor11', 'Minor 11th'), ('13', '13th'), ('major13', 'Major 13th'), ('minor13', 'Minor 13th'), ('7#5', '7th ♯5'), ('7b5', '7th ♭5'), ('7#9', '7th ♯9'), ('7b9', '7th ♭9'), ('7#11', '7th ♯11'), ('7b13', '7th ♭13')], help_text="Chord type (e.g., 'major', 'minor', 'diminished')", max_length=20),
        ),
    ]
